### ISSUE TITLE
変数名をNengajoからTicketに変更する

### ISSUE THREAD

**Issue by yu23ki14** [henkaku-center/henkaku-ticket-contract#1]

**Comment by RyuKiyo66** [comment]
今日と明日は時間があるのでやってみたいです。

**Comment by RyuKiyo66** [comment]
この編集をする場合、以前のNengajoContractがLocalPCにあり、改めて、TicketContractをLocal PCにForkできません。CloneしてもNengajoContractのCloneになってしまいます。一応私のブランチでは編集できているのですが、どうやってプルリクしたらよいでしょうか？

**Comment by yu23ki14** [comment]
@RyuKiyo66 
git clone https://github.com/henkaku-center/henkaku-ticket-contract.git
は実行しているという認識であっていますか？

**Comment by RyuKiyo66** [comment]
コマンドラインでやっていなかったのでもう一度やってみます。

**Comment by RyuKiyo66** [comment]
@yu23ki14 Pushできる権限がありません。
