### ISSUE TITLE
レベニューシェア

### ISSUE THREAD

**Issue by yawn-c111** [henkaku-center/henkaku-ticket-contract#20]
チケット代金支払いと同時に、複数のウォレットにトークンがシェアされるようにする。

- [x] TicketInfoストラクトに
  - 関係者たちのウォレットの配列
  - 関係者たちに支払う金額の配列

　　を追加

- [x] `registerTicket()`の引数に上記2つを追加して、`TicketInfo[] private registeredTickets`に保存する
- [x] `mint()`が実行された時、関係者たちのウォレットにそれぞれに支払う金額がトランスファーされるコードを追加

**Comment by RyuKiyo66** [comment]
後々のことを考えて、関係者たちのDiscordIDとかも配列で持っていいた方がいいかもしれません。
